INSERT INTO t_color (name, value) VALUES ('GREEN SEA', '#16a085');
INSERT INTO t_color (name, value) VALUES ('NEPHRITIS', '#27ae60');
INSERT INTO t_color (name, value) VALUES ('BELIZE HOLE', '#2980b9');
INSERT INTO t_color (name, value) VALUES ('MIDNIGHT', '#2c3e50');
INSERT INTO t_color (name, value) VALUES ('ASBESTOS', '#7f8c8d');
INSERT INTO t_color (name, value) VALUES ('WISTERIA', '#8e44ad');
INSERT INTO t_color (name, value) VALUES ('SILVER', '#bdc3c7');
INSERT INTO t_color (name, value) VALUES ('POMEGRANATE', '#c0392b');
INSERT INTO t_color (name, value) VALUES ('PUMPKIN', '#d35400');
INSERT INTO t_color (name, value) VALUES ('Dark Salmon', '#efa48b');
INSERT INTO t_color (name, value) VALUES ('ORANGE', '#f39c12');
