
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/tams?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 30000

logging:
  level:
    com.lhd.tams: debug
